# This is a basic workflow to help you get started with Actions

name: Push main to public

on:
  push:
    branches: [ "test" ]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      # Runs a set of commands using the runners shell
      - name: Push to public remote
        # env:
          # token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          # git config user.name "cgps-admin"
          # git config user.email "cgps.dev@gmail.com"
          git remote add public https://github.com/pathogenwatch-oss/amr-libraries.git
          # git remote set-url origin "https://oauth2:${token}@gitlab.com/cgps/pathogenwatch/website.git"
          git push -u public main --follow-tags
