# This is a basic workflow to help you get started with Actions

name: Push main to public

on:
  push:
    branches: [ "test" ]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "pathogenwatch/amr-libraries"
          source_branch: "main"
          destination_repo: "https://cgps-admin:${{ secrets.GIT_PUSH_TOKEN }}github.com/pathogenwatch-oss/amr-libraries.git"
          destination_branch: "main"
          # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          # destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
    # steps:
    #   - uses: actions/checkout@v3
    #     with:
    #       ref: main
    #       fetch-depth: 0
    #   # Runs a set of commands using the runners shell
    #   - name: Push to public remote
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       git config user.name "cgps-admin"
    #       git config user.email "cgps.dev@gmail.com"
    #       git push set-url main https://cgps-admin:${GITHUB_TOKEN}@github.com/pathogenwatch-oss/amr-libraries.git --follow-tags
